---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zane.
--- DateTime: 2018/9/26 0026 下午 21:01
---

local skynet = require('skynet')

local max_client = 1000
local tcp_port = 8888
local ws_port = 7777
local debug_port = 8000

-- TCP SOCKET模式
local tcpdog = function()

    local watchdog = skynet.newservice("watchdog")

    skynet.call(watchdog, "lua", "start", {
        port = tcp_port,
        maxclient = max_client,
        nodelay = true,
    })

    skynet.error("tcp socket watchdog listen on", tcp_port)
end

-- WEB SOCKET模式
local wsdog = function()

    local wswatchdog = skynet.newservice("wswatchdog")

    skynet.call(wswatchdog, "lua", "start", {
        port = ws_port,
        maxclient = max_client,
        nodelay = true,
    })

    skynet.error("web socket  watchdog listen on", ws_port)
end


-- 启动游戏服务
skynet.start(function()

    skynet.error("Server start")

    if not skynet.getenv "daemon" then
        skynet.newservice("console")
    end

    skynet.newservice("debug_console",debug_port)

    tcpdog()

    wsdog()

    skynet.newservice("pbc")

    skynet.exit()

end)