---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zane.
--- DateTime: 2018/10/24 0024 下午 20:37
---

local M = {}

local proto_map = {}

setmetatable(M, {
    __index = function(t, k)
        return function()
            print("unknown field from prototypes: ", k)
        end
    end
})



--游戏登录
M.main_login = 100
M.sub_c2s_login = 1     --登录请求
M.sub_s2c_login = 2     --登录返回



proto_map[M.main_login] = "Login"
proto_map[M.sub_c2s_login] = "c2s_login"
proto_map[M.sub_s2c_login] = "s2c_login"

M.get_proto_name = function(key)
    return proto_map[key]
end

M.wapper_proto_name = function(mainId, subId)
    local main_name = M.get_proto_name(mainId)
    local sub_name = M.get_proto_name(subId)
    return string.format("%s.%s", main_name, sub_name)
end

return M
